insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '波多黎各(美)' , 'Puerto Rico' , 'boduolige(mei)' ,'PR' ,'+1');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '巴勒斯坦' , 'Palestinian Territory (the Occupied)' , 'balesitan' ,'PS' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '葡萄牙' , 'Portugal' , 'putaoya' ,'PT' ,'+351');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '帕劳(美)' , 'Palau' , 'palao(mei)' ,'PW' ,'+680');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '巴拉圭' , 'Paraguay' , 'balagui' ,'PY' ,'+595');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '卡塔尔' , 'Qatar' , 'kataer' ,'QA' ,'+974');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '安道尔' , 'Andorra' , 'andaoer' ,'AD' ,'+376');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '阿拉伯联合酋长国' , 'United Arab Emirates (the)' , 'alabolianheqiuchangguo' ,'AE' ,'+971');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '阿富汗' , 'Afghanistan' , 'afuhan' ,'AF' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '安提瓜和巴布达' , 'Antigua and Barbuda' , 'antiguahebabuda' ,'AG' ,'+1 (268)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '安圭拉岛(英)' , 'Anguilla' , 'anguiladao(ying)' ,'AI' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '阿尔巴尼亚' , 'Albania' , 'aerbaniya' ,'AL' ,'+355');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '亚美尼亚' , 'Armenia' , 'yameiniya' ,'AM' ,'+374');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '荷属安的列斯群岛' , 'Netherlands Antilles (the)' , 'heshuandeliesiqundao' ,'AN' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '安哥拉' , 'Angola' , 'angela' ,'AO' ,'+244');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '南极' , 'Antarctica' , 'nanji' ,'AQ' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '阿根廷' , 'Argentina' , 'agenting' ,'AR' ,'+54');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '东萨摩亚(美)' , 'American Samoa' , 'dongsamoya(mei)' ,'AS' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '奥地利' , 'Austria' , 'aodili' ,'AT' ,'+43');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '留尼汪岛' , 'Réunion' , 'liuniwangdao' ,'RE' ,'+262');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '澳大利亚' , 'Australia' , 'aodaliya' ,'AU' ,'+61');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '阿鲁巴岛' , 'Aruba' , 'alubadao' ,'AW' ,'+297');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '奥兰群岛' , 'Aland Islands' , 'aolanqundao' ,'AX' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '阿塞拜疆' , 'Azerbaijan' , 'asaibaijiang' ,'AZ' ,'+994');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '罗马尼亚' , 'Romania' , 'luomaniya' ,'RO' ,'+40');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '波斯尼亚和黑塞哥维那' , 'Bosnia and Herzegovina' , 'bosiniyaheheisaigeweina' ,'BA' ,'+387');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '巴巴多斯' , 'Barbados' , 'babaduosi' ,'BB' ,'+1 (246)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '塞尔维亚' , 'Serbia' , 'saierweiya' ,'RS' ,'+381');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '孟加拉国' , 'Bangladesh' , 'mengjialaguo' ,'BD' ,'+880');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '比利时' , 'Belgium' , 'bilishi' ,'BE' ,'+32');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '俄罗斯' , 'Russian Federation (the)' , 'eluosi' ,'RU' ,'+7');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '布基纳法索' , 'Burkina Faso' , 'bujinafasuo' ,'BF' ,'+226');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '保加利亚' , 'Bulgaria' , 'baojialiya' ,'BG' ,'+359');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '卢旺达' , 'Rwanda' , 'luwangda' ,'RW' ,'+250');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '巴林' , 'Bahrain' , 'balin' ,'BH' ,'+973');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '布隆迪' , 'Burundi' , 'bulongdi' ,'BI' ,'+257');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '贝宁' , 'Benin' , 'beining' ,'BJ' ,'+229');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '百慕大群岛(英)' , 'Bermuda' , 'baimudaqundao(ying)' ,'BM' ,'+1 (441)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '文莱' , 'Brunei Darussalam' , 'wenlai' ,'BN' ,'+673');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '玻利维亚' , 'Bolivia' , 'boliweiya' ,'BO' ,'+591');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '沙特阿拉伯' , 'Saudi Arabia' , 'shatealabo' ,'SA' ,'+966');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '所罗门群岛' , 'Solomon Islands (the)' , 'suoluomenqundao' ,'SB' ,'+677');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '巴西' , 'Brazil' , 'baxi' ,'BR' ,'+55');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '塞舌尔' , 'Seychelles' , 'saisheer' ,'SC' ,'+248');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '巴哈马国' , 'Bahamas (The)' , 'bahamaguo' ,'BS' ,'+1 (242)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '不丹' , 'Bhutan' , 'budan' ,'BT' ,'+975');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '瑞典' , 'Sweden' , 'ruidian' ,'SE' ,'+46');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '布韦岛' , 'Bouvet Island' , 'buweidao' ,'BV' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '新加坡' , 'Singapore' , 'xinjiapo' ,'SG' ,'+65');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '博茨瓦纳' , 'Botswana' , 'bociwana' ,'BW' ,'+267');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '圣赫勒拿' , 'Saint Helena' , 'shenghelena' ,'SH' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '斯洛文尼亚' , 'Slovenia' , 'siluowenniya' ,'SI' ,'+386');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '白俄罗斯' , 'Belarus' , 'baieluosi' ,'BY' ,'+375');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '斯瓦尔巴群岛(挪)' , 'Svalbard and Jan Mayen' , 'siwaerbaqundao(nuo)' ,'SJ' ,'+47');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '伯利兹' , 'Belize' , 'bolizi' ,'BZ' ,'+501');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '斯洛伐克' , 'Slovakia' , 'siluofake' ,'SK' ,'+421');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '塞拉利昂' , 'Sierra Leone' , 'sailaliang' ,'SL' ,'+232');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '圣马力诺' , 'San Marino' , 'shengmalinuo' ,'SM' ,'+378');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '塞内加尔' , 'Senegal' , 'saineijiaer' ,'SN' ,'+221');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '索马里' , 'Somalia' , 'suomali' ,'SO' ,'+252');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '加拿大' , 'Canada' , 'jianada' ,'CA' ,'+1');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '苏里南' , 'Suriname' , 'sulinan' ,'SR' ,'+597');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '科科斯岛' , 'Cocos (Keeling) Islands (the)' , 'kekesidao' ,'CC' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '刚果(金)' , 'Congo (the Democratic Republic of the)' , 'gangguo(jin)' ,'CD' ,'+243');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '圣多美和普林西比' , 'Sao Tome and Principe' , 'shengduomeihepulinxibi' ,'ST' ,'+239');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '萨尔瓦多' , 'El Salvador' , 'saerwaduo' ,'SV' ,'+503');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '中非' , 'Central African Republic (the)' , 'zhongfei' ,'CF' ,'+236');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '刚果' , 'Congo' , 'gangguo' ,'CG' ,'+242');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '瑞士' , 'Switzerland' , 'ruishi' ,'CH' ,'+41');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '科特迪瓦' , 'Côte d Ivoire' , 'ketediwa' ,'CI' ,'+225');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '斯威士兰' , 'Swaziland' , 'siweishilan' ,'SZ' ,'+268');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '科克群岛(新)' , 'Cook Islands (the)' , 'kekequndao(xin)' ,'CK' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '智利' , 'Chile' , 'zhili' ,'CL' ,'+56');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '喀麦隆' , 'Cameroon' , 'kamailong' ,'CM' ,'+237');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '中国' , 'China' , 'zhongguo' ,'CN' ,'+86');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '哥伦比亚' , 'Colombia' , 'gelunbiya' ,'CO' ,'+57');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '哥斯达黎加' , 'Costa Rica' , 'gesidalijia' ,'CR' ,'+506');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '特克斯和凯科斯群岛(英)' , 'Turks and Caicos Islands (the)' , 'tekesihekaikesiqundao(ying)' ,'TC' ,'+1 (649)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '乍得' , 'Chad' , 'zhade' ,'TD' ,'+235');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '法属南部和南极领地' , 'French Southern Territories (the)' , 'fashunanbuhenanjilingdi' ,'TF' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '多哥' , 'Togo' , 'duoge' ,'TG' ,'+228');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '佛得角' , 'Cape Verde' , 'fodejiao' ,'CV' ,'+238');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '泰国' , 'Thailand' , 'taiguo' ,'TH' ,'+66');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '圣诞岛' , 'Christmas Island' , 'shengdandao' ,'CX' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '塞浦路斯' , 'Cyprus' , 'saipulusi' ,'CY' ,'+357');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '塔吉克斯坦' , 'Tajikistan' , 'tajikesitan' ,'TJ' ,'+992');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '捷克' , 'Czech Republic (the)' , 'jieke' ,'CZ' ,'+420');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '托克劳群岛(新)' , 'Tokelau' , 'tuokelaoqundao(xin)' ,'TK' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '东帝汶' , 'Timor-Leste' , 'dongdiwen' ,'TL' ,'+670');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '土库曼斯坦' , 'Turkmenistan' , 'tukumansitan' ,'TM' ,'+993');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '突尼斯' , 'Tunisia' , 'tunisi' ,'TN' ,'+216');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '汤加' , 'Tonga' , 'tangjia' ,'TO' ,'+676');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '土耳其' , 'Turkey' , 'tuerqi' ,'TR' ,'+90');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '特立尼达和多巴哥' , 'Trinidad and Tobago' , 'telinidaheduobage' ,'TT' ,'+1 (868)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '德国' , 'Germany' , 'deguo' ,'DE' ,'+49');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '图瓦卢' , 'Tuvalu' , 'tuwalu' ,'TV' ,'+688');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '吉布提' , 'Djibouti' , 'jibuti' ,'DJ' ,'+253');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '坦桑尼亚' , 'Tanzania,United Republic of' , 'tansangniya' ,'TZ' ,'+255');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '丹麦' , 'Denmark' , 'danmai' ,'DK' ,'+45');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '多米尼克国' , 'Dominica' , 'duominikeguo' ,'DM' ,'+1 (767)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '多米尼加共和国' , 'Dominican Republic (the)' , 'duominijiagongheguo' ,'DO' ,'+1 (8)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '乌克兰' , 'Ukraine' , 'wukelan' ,'UA' ,'+380');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '乌干达' , 'Uganda' , 'wuganda' ,'UG' ,'+256');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '阿尔及利亚' , 'Algeria' , 'aerjiliya' ,'DZ' ,'+213');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '美国本土外小岛屿' , 'United States Minor Outlying Islands (the)' , 'meiguobentuwaixiaodaoyu' ,'UM' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '厄瓜多尔' , 'Ecuador' , 'eguaduoer' ,'EC' ,'+593');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '美国' , 'United States (the)' , 'meiguo' ,'US' ,'+1');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '爱沙尼亚' , 'Estonia' , 'aishaniya' ,'EE' ,'+372');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '埃及' , 'Egypt' , 'aiji' ,'EG' ,'+20');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '西撒哈拉' , 'Western Sahara' , 'xisahala' ,'EH' ,'+212');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '乌拉圭' , 'Uruguay' , 'wulagui' ,'UY' ,'+598');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '乌兹别克斯坦' , 'Uzbekistan' , 'wuzibiekesitan' ,'UZ' ,'+998');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '梵蒂冈' , 'Holy See (the) [Vatican City State]' , 'fandigang' ,'VA' ,'+39 (066)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '厄立特里亚' , 'Eritrea' , 'eliteliya' ,'ER' ,'+291');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '圣文森特岛(英)' , 'Saint Vincent and the Grenadines' , 'shengwensentedao(ying)' ,'VC' ,'+1 (784)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '西班牙' , 'Spain' , 'xibanya' ,'ES' ,'+34');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '埃塞俄比亚' , 'Ethiopia' , 'aisaiebiya' ,'ET' ,'+251');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '委内瑞拉' , 'Venezuela' , 'weineiruila' ,'VE' ,'+58');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '维尔京群岛(英)' , 'Virgin Islands (British)' , 'weierjingqundao(ying)' ,'VG' ,'+1 (284)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '维尔京群岛(美)' , 'Virgin Islands (U.S.)' , 'weierjingqundao(mei)' ,'VI' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '越南' , 'Viet Nam' , 'yuenan' ,'VN' ,'+84');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '瓦努阿图' , 'Vanuatu' , 'wanuatu' ,'VU' ,'+678');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '芬兰' , 'Finland' , 'fenlan' ,'FI' ,'+358');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '斐济' , 'Fiji' , 'feiji' ,'FJ' ,'+679');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '福克兰群岛' , 'Falkland Islands (the) [Malvinas]' , 'fukelanqundao' ,'FK' ,'+500');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '密克罗尼西亚(美)' , 'Micronesia (the Federated States of)' , 'mikeluonixiya(mei)' ,'FM' ,'+691');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '法罗群岛(丹)' , 'Faroe Islands (the)' , 'faluoqundao(dan)' ,'FO' ,'+298');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '法国' , 'France' , 'faguo' ,'FR' ,'+33');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '瓦里斯和富士那群岛(法)' , 'Wallis and Futuna' , 'walisihefushinaqundao(fa)' ,'WF' ,'+681');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '加蓬' , 'Gabon' , 'jiapeng' ,'GA' ,'+241');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '英国' , 'United Kingdom (the)' , 'yingguo' ,'GB' ,'+44');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '西萨摩亚' , 'Samoa' , 'xisamoya' ,'WS' ,'+685');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '格林纳达' , 'Grenada' , 'gelinnada' ,'GD' ,'+1 (473)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '格鲁吉亚' , 'Georgia' , 'gelujiya' ,'GE' ,'+995');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '法属圭亚那' , 'French Guiana' , 'fashuguiyana' ,'GF' ,'+594');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '根西岛(英)' , 'Guernsey' , 'genxidao(ying)' ,'GG' ,'+44');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '加纳' , 'Ghana' , 'jiana' ,'GH' ,'+233');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '直布罗陀(英)' , 'Gibraltar' , 'zhibuluotuo(ying)' ,'GI' ,'+350');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '格陵兰岛' , 'Greenland' , 'gelinglandao' ,'GL' ,'+299');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '冈比亚' , 'Gambia (The)' , 'gangbiya' ,'GM' ,'+220');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '几内亚' , 'Guinea' , 'jineiya' ,'GN' ,'+224');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '瓜德罗普岛(法)' , 'Guadeloupe' , 'guadeluopudao(fa)' ,'GP' ,'+590');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '赤道几内亚' , 'Equatorial Guinea' , 'chidaojineiya' ,'GQ' ,'+240');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '希腊' , 'Greece' , 'xila' ,'GR' ,'+30');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '危地马拉' , 'Guatemala' , 'weidimala' ,'GT' ,'+502');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '关岛(美)' , 'Guam' , 'guandao(mei)' ,'GU' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '几内亚比绍' , 'Guinea-Bissau' , 'jineiyabishao' ,'GW' ,'+245');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '圭亚那' , 'Guyana' , 'guiyana' ,'GY' ,'+592');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '赫德岛和麦克唐纳群岛' , 'Heard Island and McDonald Islands' , 'hededaohemaiketangnaqundao' ,'HM' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '洪都拉斯' , 'Honduras' , 'hongdoulasi' ,'HN' ,'+504');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '克罗地亚' , 'Croatia' , 'keluodiya' ,'HR' ,'+385');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '海地' , 'Haiti' , 'haidi' ,'HT' ,'+509');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '也门' , 'Yemen' , 'yemen' ,'YE' ,'+967');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '匈牙利' , 'Hungary' , 'xiongyali' ,'HU' ,'+36');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马约特岛' , 'Mayotte' , 'mayuetedao' ,'YT' ,'+262');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '印度尼西亚' , 'Indonesia' , 'yindunixiya' ,'ID' ,'+62');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '爱尔兰' , 'Ireland' , 'aierlan' ,'IE' ,'+353');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '以色列' , 'Israel' , 'yiselie' ,'IL' ,'+972');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马恩岛(英)' , 'Isle of Man' , 'maendao(ying)' ,'IM' ,'+44');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '印度' , 'India' , 'yindu' ,'IN' ,'+91');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '英属印度洋领地' , 'British Indian Ocean Territory (the)' , 'yingshuyinduyanglingdi' ,'IO' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '南非' , 'South Africa' , 'nanfei' ,'ZA' ,'+27');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '伊拉克' , 'Iraq' , 'yilake' ,'IQ' ,'+964');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '冰岛' , 'Iceland' , 'bingdao' ,'IS' ,'+354');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '意大利' , 'Italy' , 'yidali' ,'IT' ,'+39');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '赞比亚' , 'Zambia' , 'zanbiya' ,'ZM' ,'+260');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '泽西岛(英)' , 'Jersey' , 'zexidao(ying)' ,'JE' ,'+44');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '津巴布韦' , 'Zimbabwe' , 'jinbabuwei' ,'ZW' ,'+263');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '牙买加' , 'Jamaica' , 'yamaijia' ,'JM' ,'+1 (876)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '约旦' , 'Jordan' , 'yuedan' ,'JO' ,'+962');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '日本' , 'Japan' , 'riben' ,'JP' ,'+81');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '肯尼亚' , 'Kenya' , 'kenniya' ,'KE' ,'+254');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '吉尔吉斯斯坦' , 'Kyrgyzstan' , 'jierjisisitan' ,'KG' ,'+996');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '柬埔寨' , 'Cambodia' , 'jianpuzhai' ,'KH' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '基里巴斯' , 'Kiribati' , 'jilibasi' ,'KI' ,'+686');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '科摩罗' , 'Comoros' , 'kemoluo' ,'KM' ,'+269');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '圣克里斯托弗和尼维斯' , 'Saint Kitts and Nevis' , 'shengkelisituofuheniweisi' ,'KN' ,'+1 (869)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '韩国' , 'Korea (the Republic of)' , 'hanguo' ,'KR' ,'+82');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '科威特' , 'Kuwait' , 'keweite' ,'KW' ,'+965');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '开曼群岛(英)' , 'Cayman Islands (the)' , 'kaimanqundao(ying)' ,'KY' ,'+1 (345)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '哈萨克斯坦' , 'Kazakhstan' , 'hasakesitan' ,'KZ' ,'+77');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '老挝' , 'Lao People s Democratic Republic (the)' , 'laowo' ,'LA' ,'+856');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '黎巴嫩' , 'Lebanon' , 'libanen' ,'LB' ,'+961');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '圣卢西亚' , 'Saint Lucia' , 'shengluxiya' ,'LC' ,'+1 (758)');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '列支敦士登' , 'Liechtenstein' , 'liezhidunshideng' ,'LI' ,'+423');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '斯里兰卡' , 'Sri Lanka' , 'sililanka' ,'LK' ,'+94');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '利比里亚' , 'Liberia' , 'libiliya' ,'LR' ,'+231');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '莱索托' , 'Lesotho' , 'laisuotuo' ,'LS' ,'+266');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '立陶宛' , 'Lithuania' , 'litaowan' ,'LT' ,'+370');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '卢森堡' , 'Luxembourg' , 'lusenbao' ,'LU' ,'+352');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '拉脱维亚' , 'Latvia' , 'latuoweiya' ,'LV' ,'+371');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '利比亚' , 'Libyan Arab Jamahiriya (the)' , 'libiya' ,'LY' ,'+218');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '摩洛哥' , 'Morocco' , 'moluoge' ,'MA' ,'+212');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '摩纳哥' , 'Monaco' , 'monage' ,'MC' ,'+377');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '摩尔多瓦' , 'Moldova (the Republic of)' , 'moerduowa' ,'MD' ,'+373');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '黑山' , 'Montenegro' , 'heishan' ,'ME' ,'+382');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马达加斯加' , 'Madagascar' , 'madajiasijia' ,'MG' ,'+261');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马绍尔群岛' , 'Marshall Islands (the)' , 'mashaoerqundao' ,'MH' ,'+692');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '北马其顿' , 'Macedonia (the former Yugoslav Republic of)' , 'beimaqidun' ,'MK' ,'+389');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马里' , 'Mali' , 'mali' ,'ML' ,'+223');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '缅甸' , 'Myanmar' , 'miandian' ,'MM' ,'+95');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '蒙古' , 'Mongolia' , 'menggu' ,'MN' ,'+976');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马里亚纳群岛' , 'Northern Mariana Islands (the)' , 'maliyanaqundao' ,'MP' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马提尼克(法)' , 'Martinique' , 'matinike(fa)' ,'MQ' ,'+596');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '毛里塔尼亚' , 'Mauritania' , 'maolitaniya' ,'MR' ,'+222');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '蒙特塞拉特岛(英)' , 'Montserrat' , 'mengtesailatedao(ying)' ,'MS' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马耳他' , 'Malta' , 'maerta' ,'MT' ,'+356');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '毛里求斯' , 'Mauritius' , 'maoliqiusi' ,'MU' ,'+230');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马尔代夫' , 'Maldives' , 'maerdaifu' ,'MV' ,'+960');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马拉维' , 'Malawi' , 'malawei' ,'MW' ,'+265');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '墨西哥' , 'Mexico' , 'moxige' ,'MX' ,'+52');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '马来西亚' , 'Malaysia' , 'malaixiya' ,'MY' ,'+60');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '莫桑比克' , 'Mozambique' , 'mosangbike' ,'MZ' ,'+258');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '纳米比亚' , 'Namibia' , 'namibiya' ,'NA' ,'+264');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '新喀里多尼亚群岛(法)' , 'New Caledonia' , 'xinkaliduoniyaqundao(fa)' ,'NC' ,'+687');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '尼日尔' , 'Niger (the)' , 'nirier' ,'NE' ,'+227');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '诺福克岛(澳)' , 'Norfolk Island' , 'nuofukedao(ao)' ,'NF' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '尼日利亚' , 'Nigeria' , 'niriliya' ,'NG' ,'+234');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '尼加拉瓜' , 'Nicaragua' , 'nijialagua' ,'NI' ,'+505');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '荷兰' , 'Netherlands (the)' , 'helan' ,'NL' ,'+31');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '挪威' , 'Norway' , 'nuowei' ,'NO' ,'+47');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '尼泊尔' , 'Nepal' , 'niboer' ,'NP' ,'+977');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '瑙鲁' , 'Nauru' , 'naolu' ,'NR' ,'+674');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '纽埃岛(新)' , 'Niue' , 'niuaidao(xin)' ,'NU' ,'');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '新西兰' , 'New Zealand' , 'xinxilan' ,'NZ' ,'+64');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '阿曼' , 'Oman' , 'aman' ,'OM' ,'+968');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '巴拿马' , 'Panama' , 'banama' ,'PA' ,'+507');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '秘鲁' , 'Peru' , 'bilu' ,'PE' ,'+51');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '法属波里尼西亚' , 'French Polynesia' , 'fashubolinixiya' ,'PF' ,'+689');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '巴布亚新几内亚' , 'Papua New Guinea' , 'babuyaxinjineiya' ,'PG' ,'+675');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '菲律宾' , 'Philippines (the)' , 'feilvbin' ,'PH' ,'+63');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '巴基斯坦' , 'Pakistan' , 'bajisitan' ,'PK' ,'+92');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '波兰' , 'Poland' , 'bolan' ,'PL' ,'+48');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '圣皮埃尔岛及密克隆岛' , 'Saint Pierre and Miquelon' , 'shengpiaierdaojimikelongdao' ,'PM' ,'+508');
insert into `app_administration` (`cn_name`,`en_name`,`pinyin`,`iso`,phone_prefix) VALUES ( '皮特凯恩群岛' , 'Pitcairn' , 'pitekaienqundao' ,'PN' ,'');
