INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '236','Alabama','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '237','Alaska','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '238','Arizona','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '239','Arkansas','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '240','California','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '241','Colorado','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '242','Connecticut','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '243','Delaware','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '244','Distinct of Columbia','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '245','Florida','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '246','Grorgia','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '247','Hawaii','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '248','Idaho','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '249','Illinois','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '250','Indiana','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '251','Iowa','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '252','Kansas','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '253','Kentucky','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '254','Louisiana','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '255','Maine','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '256','Maryland','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '257','Massachusetts','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '258','Michigan','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '259','Minnesota','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '260','Mississippi','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '261','Missouri','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '262','Montana','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '263','Nebraska','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '264','Nevada','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '265','New Hampshire','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '266','New Jersey','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '267','New Mexico','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '268','New York','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '269','North Carolina','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '270','North Dakota','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '271','Ohio','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '272','Oklahoma','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '273','Oregon','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '274','Pennsylvania','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '275','Rhode Island','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '276','South Carolina','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '277','South Dakota','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '278','Tennessee','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '279','Texas','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '280','Utah','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '281','Vermont','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '282','Virginia','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '283','Washington','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '284','West Virginia','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '285','Wisconsin','107');
INSERT INTO `app_administration` ( `id`,`en_name`, `parent_id`) VALUES  ( '286','Wyoming','107');