package org.example.user.pojo.dao.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.user.pojo.dao.dao.model.AppShippingAddress;
import org.example.user.pojo.dao.dao.model.AppShippingAddressExample;

public interface AppShippingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_shipping_address
     *
     * @mbg.generated Thu Jun 02 15:38:01 CST 2022
     */
    long countByExample(AppShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_shipping_address
     *
     * @mbg.generated Thu Jun 02 15:38:01 CST 2022
     */
    int deleteByExample(AppShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_shipping_address
     *
     * @mbg.generated Thu Jun 02 15:38:01 CST 2022
     */
    int insert(AppShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_shipping_address
     *
     * @mbg.generated Thu Jun 02 15:38:01 CST 2022
     */
    int insertSelective(AppShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_shipping_address
     *
     * @mbg.generated Thu Jun 02 15:38:01 CST 2022
     */
    List<AppShippingAddress> selectByExample(AppShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_shipping_address
     *
     * @mbg.generated Thu Jun 02 15:38:01 CST 2022
     */
    int updateByExampleSelective(@Param("record") AppShippingAddress record, @Param("example") AppShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_shipping_address
     *
     * @mbg.generated Thu Jun 02 15:38:01 CST 2022
     */
    int updateByExample(@Param("record") AppShippingAddress record, @Param("example") AppShippingAddressExample example);
}